version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:5000
      - USER_SERVICE_URL=http://user-service:3002
      - POST_SERVICE_URL=http://post-service:3003
      - COMMENT_SERVICE_URL=http://comment-service:3004
      - LIKE_SERVICE_URL=http://like-service:3005
      - MESSAGE_SERVICE_URL=http://message-service:3006
      - NOTIFICATION_SERVICE_URL=http://notification-service:3007
    depends_on:
      - auth-service
      - user-service
      - post-service
      - comment-service
      - like-service
      - message-service
      - notification-service

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your_jwt_secret
      - ACCESS_TOKEN_SECRET=your_access_token_secret
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret
      - ACCESS_TOKEN_EXPIRY=15m
      - REFRESH_TOKEN_EXPIRY=7d
      - EMAIL_VERIFICATION_SECRET=your_email_verification_secret
      - RESET_TOKEN_SECRET=your_reset_token_secret
      - FRONTEND_URL=http://localhost:3000
      - INTER_SERVICE_API_KEY=socialka-inter-service-key-2024
      - USER_SERVICE_URL=http://user-service:3002
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASS=your-app-password
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=user_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - INTER_SERVICE_API_KEY=socialka-inter-service-key-2024
    depends_on:
      - postgres

  post-service:
    build: ./post-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=post_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres

  comment-service:
    build: ./comment-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=comment_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres

  like-service:
    build: ./like-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=like_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres

  message-service:
    build: ./message-service
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=message_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres

  notification-service:
    build: ./notification-service
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=notification_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 